/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flatnote;

import java.io.File; 
/**
 *
 * @author joeordie
 */
public class FrmMainWindow extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainWindow
     */
    public FrmMainWindow() {
        initComponents();
        //setSize(400,300);
        setResizable(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        btnSelectNote.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNotebook = new javax.swing.JLabel();
        lblNoteName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editNoteBody = new javax.swing.JEditorPane();
        btnNewNotebook = new javax.swing.JButton();
        btnNewNote = new javax.swing.JButton();
        btnSaveNote = new javax.swing.JButton();
        btnDeleteNote = new javax.swing.JButton();
        btnSelectNote = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbxNoteName = new javax.swing.JComboBox<>();
        cbxNotebookName = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menFileSelectDirectory = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNotebook.setText("Notebook");

        lblNoteName.setText("Note Name");

        jScrollPane1.setViewportView(editNoteBody);

        btnNewNotebook.setText("New");
        btnNewNotebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewNotebookActionPerformed(evt);
            }
        });

        btnNewNote.setText("New");
        btnNewNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewNoteActionPerformed(evt);
            }
        });

        btnSaveNote.setText("Save");
        btnSaveNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveNoteMouseClicked(evt);
            }
        });
        btnSaveNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNoteActionPerformed(evt);
            }
        });

        btnDeleteNote.setText("Delete");
        btnDeleteNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNoteActionPerformed(evt);
            }
        });

        btnSelectNote.setText("Search");

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbxNoteName.setEditable(true);
        cbxNoteName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "new" }));

        cbxNotebookName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "new" }));

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        menFileSelectDirectory.setText("File");

        jMenuItem1.setText("Select Directory");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menFileSelectDirectory.add(jMenuItem1);

        jMenuBar1.add(menFileSelectDirectory);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNotebook)
                            .addComponent(lblNoteName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxNoteName, 0, 338, Short.MAX_VALUE)
                            .addComponent(cbxNotebookName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNewNotebook)
                            .addComponent(btnNewNote)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSelectNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveNote)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotebook)
                    .addComponent(btnNewNotebook)
                    .addComponent(cbxNotebookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoteName)
                    .addComponent(btnNewNote)
                    .addComponent(jButton1)
                    .addComponent(cbxNoteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveNote)
                    .addComponent(btnDeleteNote)
                    .addComponent(btnSelectNote))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void DisplayNote(String[] strNoteComp){
        cbxNoteName.addItem(strNoteComp[1]);
        cbxNotebookName.addItem(strNoteComp[0]);
        editNoteBody.setText(strNoteComp[2]);
        
    }
        
    private void btnSaveNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveNoteMouseClicked
        // TODO add your handling code here:
        //String NoteComp[2];
        
    }//GEN-LAST:event_btnSaveNoteMouseClicked

    private void btnNewNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewNoteActionPerformed
        String[] strNoteComp = new String[2];
        strNoteComp[0] = String.valueOf(cbxNotebookName.getSelectedItem());
        strNoteComp[1] = String.valueOf(cbxNoteName.getSelectedItem());
        if (FlatNote.NewNote(strNoteComp) == 1 ){
            DisplayNote(FlatNote.readNote(strNoteComp));
        }
        
    }//GEN-LAST:event_btnNewNoteActionPerformed

    private void btnSaveNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNoteActionPerformed
        // TODO add your handling code here:
        String[] strNoteComp = new String[3];
        strNoteComp[0] = String.valueOf(cbxNotebookName.getSelectedItem());
        strNoteComp[1] = String.valueOf(cbxNoteName.getSelectedItem());
        strNoteComp[2] = editNoteBody.getText();
        FlatNote.SaveNote(strNoteComp);
                
    }//GEN-LAST:event_btnSaveNoteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FlatNote.SelectDirectory();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnDeleteNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNoteActionPerformed
        String[] strNoteComp = new String[2];
        strNoteComp[0] = String.valueOf(cbxNotebookName.getSelectedItem());
        strNoteComp[1] = String.valueOf(cbxNoteName.getSelectedItem());
        FlatNote.DeleteNote(strNoteComp);
                
    }//GEN-LAST:event_btnDeleteNoteActionPerformed

    private void btnNewNotebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewNotebookActionPerformed
        
        String strNotebookName = String.valueOf(cbxNotebookName.getSelectedItem());
        FlatNote.NewNotebook(strNotebookName);
    }//GEN-LAST:event_btnNewNotebookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File folder = new File(FlatNote.strFilePath+"/"+String.valueOf(cbxNotebookName.getSelectedItem()));
        cbxNoteName.removeAllItems();
        File[] listOfFiles = folder.listFiles();
        
        for (File file : listOfFiles ){
            if (file.isFile()) {
                String sawmill = file.getName();
                sawmill = sawmill.substring(0, sawmill.lastIndexOf('.'));
                cbxNoteName.addItem(sawmill);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File folder = new File(FlatNote.strFilePath);
        cbxNoteName.removeAllItems();
        File[] listOfFiles = folder.listFiles();
        
        for (File file : listOfFiles ){
            if (file.isDirectory()) {
                cbxNotebookName.addItem(file.getName());
            }    
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteNote;
    private javax.swing.JButton btnNewNote;
    private javax.swing.JButton btnNewNotebook;
    private javax.swing.JButton btnSaveNote;
    private javax.swing.JButton btnSelectNote;
    private javax.swing.JComboBox<String> cbxNoteName;
    private javax.swing.JComboBox<String> cbxNotebookName;
    public javax.swing.JEditorPane editNoteBody;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNoteName;
    private javax.swing.JLabel lblNotebook;
    private javax.swing.JMenu menFileSelectDirectory;
    // End of variables declaration//GEN-END:variables
}
